-- Create enum for daily digest processing status
CREATE TYPE digest_status AS ENUM (
  'pending',
  'processing',
  'completed',
  'failed'
);

-- Create daily_digests table
CREATE TABLE daily_digests (
  id BIGSERIAL PRIMARY KEY,

  -- Date identifier (unique per user, indexed for queries)
  digest_date DATE NOT NULL,

  -- User scoping (nullable for now, will be required when user auth is added)
  user_id BIGINT,

  -- Processing status
  status digest_status NOT NULL DEFAULT 'pending',
  error_message TEXT,

  -- Metadata (collected during scaffolding phase)
  bookmark_count INTEGER NOT NULL DEFAULT 0,
  sources_breakdown JSONB, -- {"youtube": 5, "podcast": 3, ...}
  date_range_start TIMESTAMPTZ,
  date_range_end TIMESTAMPTZ,

  -- Content (will be populated in summarization phase)
  digest_content TEXT,
  total_duration NUMERIC, -- Sum of all video/audio durations in seconds
  processing_metadata JSONB, -- Token counts, model used, etc.

  -- Timestamps
  processing_started_at TIMESTAMPTZ,
  processing_completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Constraint: one digest per date (will be per user once auth is added)
  CONSTRAINT unique_daily_digest UNIQUE(digest_date, user_id)
);

-- Create indexes for better query performance
CREATE INDEX idx_daily_digests_digest_date ON daily_digests(digest_date DESC);
CREATE INDEX idx_daily_digests_user_id ON daily_digests(user_id);
CREATE INDEX idx_daily_digests_status ON daily_digests(status);
CREATE INDEX idx_daily_digests_created_at ON daily_digests(created_at DESC);

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_daily_digests_updated_at
    BEFORE UPDATE ON daily_digests
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Add comments for documentation
COMMENT ON TABLE daily_digests IS 'Stores daily digest summaries aggregating all bookmarks and transcriptions for a given date';
COMMENT ON COLUMN daily_digests.digest_date IS 'The date this digest represents (e.g., 2025-01-12 for all bookmarks from that day)';
COMMENT ON COLUMN daily_digests.user_id IS 'User ID for per-user digests (nullable until user authentication is implemented)';
COMMENT ON COLUMN daily_digests.sources_breakdown IS 'JSONB breakdown of bookmark counts by source (e.g., {"youtube": 5, "podcast": 3})';
COMMENT ON COLUMN daily_digests.digest_content IS 'The final unified summary text generated by OpenAI (populated in Phase 2)';
COMMENT ON COLUMN daily_digests.processing_metadata IS 'JSONB metadata about processing (token counts, model, duration, etc.)';
