-- Add audio intelligence fields to transcriptions table
-- This adds columns for Deepgram's sentiment analysis, summary, and other features

-- Add sentiment enum type
CREATE TYPE sentiment_type AS ENUM ('positive', 'negative', 'neutral');

-- Add new columns to transcriptions table
ALTER TABLE transcriptions
  ADD COLUMN deepgram_summary TEXT,
  ADD COLUMN sentiment sentiment_type,
  ADD COLUMN sentiment_score DOUBLE PRECISION;

-- Add indexes for common queries
CREATE INDEX idx_transcriptions_sentiment ON transcriptions(sentiment);
CREATE INDEX idx_transcriptions_sentiment_score ON transcriptions(sentiment_score);

-- Add comments for documentation
COMMENT ON COLUMN transcriptions.deepgram_summary IS 'Summary generated by Deepgram summarization feature';
COMMENT ON COLUMN transcriptions.sentiment IS 'Average sentiment of the entire transcript (positive/negative/neutral)';
COMMENT ON COLUMN transcriptions.sentiment_score IS 'Average sentiment score from -1 (most negative) to 1 (most positive)';
