// Code generated by the Encore v1.50.7 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-memai-backend-cno2.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the memai-backend-cno2 Encore application.
 */
export default class Client {
    public readonly bookmarks: bookmarks.ServiceClient
    public readonly users: users.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.bookmarks = new bookmarks.ServiceClient(base)
        this.users = new users.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: users.AuthParams | AuthDataGenerator
}

export namespace bookmarks {
    export interface CreateBookmarkTestRequest {
        url: string
        source?: types.BookmarkSource
        title?: string
        userId?: string
    }

    export interface CreateBookmarkTestResponse {
        bookmarkId: number
        url: string
        source: string
        message: string
    }

    export interface GenerateDigestTestRequest {
        date?: string
        userId?: string
    }

    export interface GenerateDigestTestResponse {
        digest: any
        message: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.createTest = this.createTest.bind(this)
            this.generateDailyDigest = this.generateDailyDigest.bind(this)
            this.generateDigestTest = this.generateDigestTest.bind(this)
            this.get = this.get.bind(this)
            this.getDailyDigest = this.getDailyDigest.bind(this)
            this.getDetails = this.getDetails.bind(this)
            this.list = this.list.bind(this)
            this.listDailyDigests = this.listDailyDigests.bind(this)
            this.remove = this.remove.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * CREATE - Add a new bookmark
         */
        public async create(params: types.CreateBookmarkRequest): Promise<types.BookmarkResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/bookmarks`, JSON.stringify(params))
            return await resp.json() as types.BookmarkResponse
        }

        /**
         * CREATE BOOKMARK (TEST) - No auth required
         * For local development and E2E testing only
         */
        public async createTest(params: CreateBookmarkTestRequest): Promise<CreateBookmarkTestResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/test/bookmarks`, JSON.stringify(params))
            return await resp.json() as CreateBookmarkTestResponse
        }

        /**
         * GENERATE DAILY DIGEST - Generate or retrieve daily digest for a date
         * (Used for manual triggering with optional date parameter)
         */
        public async generateDailyDigest(params: types.GenerateDailyDigestRequest): Promise<types.GenerateDailyDigestResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/digests/generate`, JSON.stringify(params))
            return await resp.json() as types.GenerateDailyDigestResponse
        }

        /**
         * GENERATE DAILY DIGEST (TEST) - No auth required
         * For local development and E2E testing only
         */
        public async generateDigestTest(params: GenerateDigestTestRequest): Promise<GenerateDigestTestResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/test/digests/generate`, JSON.stringify(params))
            return await resp.json() as GenerateDigestTestResponse
        }

        /**
         * READ - Get a bookmark by ID
         */
        public async get(id: number): Promise<types.BookmarkResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/bookmarks/${encodeURIComponent(id)}`)
            return await resp.json() as types.BookmarkResponse
        }

        /**
         * GET DAILY DIGEST - Get digest for a specific date
         */
        public async getDailyDigest(date: string, params: types.GetDailyDigestRequest): Promise<types.GetDailyDigestResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "user_id": params["user_id"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/digests/${encodeURIComponent(date)}`, undefined, {query})
            return await resp.json() as types.GetDailyDigestResponse
        }

        /**
         * GET DETAILS - Get a bookmark with all enriched data (transcription, etc.)
         */
        public async getDetails(id: number): Promise<types.BookmarkDetailsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/bookmarks/${encodeURIComponent(id)}/details`)
            return await resp.json() as types.BookmarkDetailsResponse
        }

        /**
         * LIST - Get all bookmarks with pagination and filtering
         */
        public async list(params: types.ListBookmarksRequest): Promise<types.ListBookmarksResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
                source: params.source === undefined ? undefined : String(params.source),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/bookmarks`, undefined, {query})
            return await resp.json() as types.ListBookmarksResponse
        }

        /**
         * LIST DAILY DIGESTS - List all digests with pagination
         */
        public async listDailyDigests(params: types.ListDailyDigestsRequest): Promise<types.ListDailyDigestsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:     params.limit === undefined ? undefined : String(params.limit),
                offset:    params.offset === undefined ? undefined : String(params.offset),
                "user_id": params["user_id"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/digests`, undefined, {query})
            return await resp.json() as types.ListDailyDigestsResponse
        }

        /**
         * DELETE - Delete a bookmark
         */
        public async remove(id: number): Promise<types.DeleteBookmarkResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/bookmarks/${encodeURIComponent(id)}`)
            return await resp.json() as types.DeleteBookmarkResponse
        }

        /**
         * UPDATE - Update a bookmark
         */
        public async update(id: number, params: types.UpdateBookmarkRequest): Promise<types.BookmarkResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/bookmarks/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as types.BookmarkResponse
        }
    }
}

export namespace users {
    export interface AuthParams {
        authorization: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.me = this.me.bind(this)
            this.updateProfile = this.updateProfile.bind(this)
            this.userCreated = this.userCreated.bind(this)
        }

        /**
         * Get Current User Endpoint
         * Returns the currently authenticated user's information from local database
         * 
         * GET /users/me
         * Headers: Authorization: Bearer <supabase-token>
         * Returns: { user: SafeUser }
         * 
         * NOTE: This endpoint fetches user data from YOUR database, not Supabase.
         * The JWT is validated by Supabase, then we look up additional user data locally.
         */
        public async me(): Promise<types.MeResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/me`)
            return await resp.json() as types.MeResponse
        }

        /**
         * Update Current User Profile Endpoint
         * Updates the authenticated user's profile information
         * 
         * PATCH /users/me
         * Headers: Authorization: Bearer <supabase-token>
         * Body: { name?: string }
         * Returns: { user: SafeUser }
         * 
         * NOTE: This endpoint updates the user's profile in our local database.
         * Email changes should be handled directly via Supabase client SDK.
         */
        public async updateProfile(params: types.UpdateProfileRequest): Promise<types.UpdateProfileResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/users/me`, JSON.stringify(params))
            return await resp.json() as types.UpdateProfileResponse
        }

        /**
         * Custom Access Token Hook
         * Called by Supabase before issuing a JWT token
         * 
         * Flow:
         * 1. User signs up/logs in via Supabase
         * 2. Supabase calls this hook BEFORE issuing the JWT
         * 3. We sync the user to our local database
         * 4. We return updated claims including our custom claim
         * 5. Supabase issues the JWT with the updated claims
         * 
         * POST /webhooks/auth/user-created
         * No authentication required (validates via Supabase webhook signature)
         * 
         * @param payload Custom Access Token hook payload with user_id and existing claims
         * @returns Updated claims object with local_db_synced added
         */
        public async userCreated(params: types.CustomAccessTokenHookPayload): Promise<types.CustomAccessTokenHookResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/webhooks/auth/user-created`, JSON.stringify(params))
            return await resp.json() as types.CustomAccessTokenHookResponse
        }
    }
}

export namespace types {
    export interface Bookmark {
        id: number
        "user_id": string
        url: string
        title: string | null
        source: BookmarkSource
        "client_time": string
        metadata: { [key: string]: any } | null
        "created_at": string
        "updated_at": string
    }

    export interface BookmarkDetailsResponse {
        bookmark: Bookmark
        transcription: TranscriptionDetails | null
    }

    export interface BookmarkResponse {
        bookmark: Bookmark
    }

    export type BookmarkSource = "youtube" | "podcast" | "reddit" | "twitter" | "linkedin" | "blog" | "web" | "other"

    export interface CreateBookmarkRequest {
        url: string
        title?: string
        source?: BookmarkSource
        "client_time": string
        metadata?: { [key: string]: any }
    }

    export interface CustomAccessTokenHookPayload {
        /**
         * User ID attempting to sign in
         */
        "user_id": string

        /**
         * Existing JWT claims that will be included in the token
         * You must preserve all existing claims and can add custom ones
         */
        claims: { [key: string]: any }

        /**
         * Authentication method used (password, oauth, otp, etc.)
         */
        "authentication_method": string
    }

    export interface CustomAccessTokenHookResponse {
        /**
         * Updated claims object (must include all required claims)
         */
        claims: { [key: string]: any }
    }

    export interface DailyDigest {
        id: number
        "digest_date": string
        "user_id": string | null
        status: DigestStatus
        "error_message": string | null
        /**
         * Metadata
         */
        "bookmark_count": number

        "sources_breakdown": SourcesBreakdown | null
        "date_range_start": string | null
        "date_range_end": string | null
        /**
         * Content (populated in Phase 2)
         */
        "digest_content": string | null

        "total_duration": number | null
        "processing_metadata": ProcessingMetadata | null
        /**
         * Timestamps
         */
        "processing_started_at": string | null

        "processing_completed_at": string | null
        "created_at": string
        "updated_at": string
    }

    export interface DeleteBookmarkResponse {
        success: boolean
    }

    export type DigestStatus = "pending" | "processing" | "completed" | "failed"

    export interface GenerateDailyDigestRequest {
        /**
         * Optional date to generate digest for (defaults to yesterday)
         */
        date?: string

        /**
         * Optional user_id for future scoping (not used yet)
         */
        "user_id"?: string
    }

    export interface GenerateDailyDigestResponse {
        digest: DailyDigest
        message: string
    }

    export interface GetDailyDigestRequest {
        "user_id"?: string
    }

    export interface GetDailyDigestResponse {
        digest: DailyDigest | null
    }

    export interface ListBookmarksRequest {
        limit?: number
        offset?: number
        source?: BookmarkSource
    }

    export interface ListBookmarksResponse {
        bookmarks: Bookmark[]
        total: number
    }

    export interface ListDailyDigestsRequest {
        limit?: number
        offset?: number
        "user_id"?: string
    }

    export interface ListDailyDigestsResponse {
        digests: DailyDigest[]
        total: number
    }

    export interface MeResponse {
        user: SafeUser
    }

    export interface ProcessingMetadata {
        tokenCount?: number
        modelUsed?: string
        processingDurationMs?: number
        summarizationStrategy?: string
        errorDetails?: string
    }

    export interface SafeUser {
        id: string
        email: string
        name: string | null
        "migrated_to_supabase": boolean
        "created_at": string
        "updated_at": string
    }

    export interface SourcesBreakdown {
        youtube?: number
        podcast?: number
        reddit?: number
        twitter?: number
        linkedin?: number
        blog?: number
        web?: number
        other?: number
    }

    export interface TranscriptionDetails {
        /**
         * Content
         */
        transcript: string | null

        "deepgram_summary": string | null
        summary: string | null
        /**
         * Sentiment analysis
         */
        sentiment: "positive" | "negative" | "neutral" | null

        "sentiment_score": number | null
        /**
         * Metadata
         */
        duration: number | null

        confidence: number | null
        status: TranscriptionStatus
        "error_message": string | null
        "created_at": string
        "updated_at": string
    }

    export type TranscriptionStatus = "pending" | "processing" | "completed" | "failed"

    export interface UpdateBookmarkRequest {
        url?: string
        title?: string
        source?: BookmarkSource
        metadata?: { [key: string]: any }
    }

    export interface UpdateProfileRequest {
        name?: string | null
    }

    export interface UpdateProfileResponse {
        user: SafeUser
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | users.AuthParams
  | Promise<users.AuthParams | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "memai-backend-cno2-Generated-TS-Client (Encore/v1.50.7)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: users.AuthParams | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
